services:
  postgres:
    image: postgres:16-alpine
    container_name: good-hamburguer-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: GoodHamburger.Api/Dockerfile
    container_name: good-hamburguer-api
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Include Error Detail=true
    ports:
      - "${API_PORT:-5078}:8080"

  view:
    build:
      context: .
      dockerfile: GoodHamburger.View/Dockerfile
    container_name: good-hamburguer-view
    restart: unless-stopped
    depends_on:
      - api
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ApiSettings__BaseUrl: http://api:8080
    ports:
      - "${VIEW_PORT:-5189}:8080"

volumes:
  postgres_data:
